### PR TITLE
feat(night_mode): Force set  background styles in NightMode

### PR DESCRIPTION
**Pull request by CharmingCheung**
I saw that when V2ex in NightMode , the background image and color of some nodes' articles is still too bright, so I tried to set the background-styles in NightMode.

Sorry, I code in JavaScript infrequently , maybe the code is bad : )

### CODE REVIEW

**Comment by VitoVan** [comment]
Thanks for your PR!

What do you think of `background-blend-mode: color;`?

It will preserve the original background image.

Page for testing:

https://www.v2ex.com/go/random

**Comment by CharmingCheung** [comment]
> Thanks for your PR!
> 
> What do you think of `background-blend-mode: color;`?
> 
> It will preserve the original background image.
> 
> Page for testing:
> 
> https://www.v2ex.com/go/random

That sounds great! 

But I think it's not work in some nodes with that way.

I had tried it, some nodes just set background color, also need set `background-color` like `#22303f`

And it let some nodes with 'pixels style' background looks not well.

Page for testing:

https://v2ex.com/go/jobs

**Comment by VitoVan** [comment]
> > Thanks for your PR!
> > What do you think of `background-blend-mode: color;`?
> > It will preserve the original background image.
> > Page for testing:
> > https://www.v2ex.com/go/random
> 
> That sounds great!
> 
> But I think it's not work in some nodes with that way.
> 
> I had tried it, some nodes just set background color, also need set `background-color` like `#22303f`
> 
> And it let some nodes with 'pixels style' background looks not well.
> 
> Page for testing:
> 
> https://v2ex.com/go/jobs

Yes, you are right.

Let's stick on your plan.

**Comment by VitoVan** [comment]
@CharmingCheung 

Thank you, the script has been upgraded to v1.1.11: 

https://greasyfork.org/en/scripts/14182-v2excellent-js

I added your name to this page:

https://vitovan.com/v2excellent.js/

If you don't feel like it, please let me know.

**Pull request merged**
